name = "analista-backend"
compatibility_date = "2024-05-01"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "analista-d1"
database_id = "31a59b6c-ae6f-41de-a268-f9d940e38058"

[vars]
JWT_SECRET = "troque-por-um-segredo-forte"
